use_frameworks!

target 'ios' do
  platform :ios, '13.0'

  pod 'Birch', path: '../', testspecs: ['Tests']
  pod 'Anchorage'
end

target 'tvos' do
  platform :tvos, '13.0'

  pod 'Birch', path: '../', testspecs: ['Tests']
end

target 'macos' do
  platform :macos, '10.15'

  pod 'Birch', path: '../', testspecs: ['Tests']
end
