default_platform :ios

platform :ios do
  lane :lint do
    pod_lib_lint(skip_tests: true)
  end

  lane :specs do |opts|
    xcode_select(opts[:xcode]) if opts[:xcode]

    case opts[:platform].to_s
    when 'tvos'
      scan(
        scheme: 'Birch-tvOS-Unit-Tests',
        derived_data_path: 'DerivedData',
        code_coverage: true,
        result_bundle: true,
        device: opts[:device]
      )
    when 'macos'
      scan(
        scheme: 'Birch-macOS-Unit-Tests',
        derived_data_path: 'DerivedData',
        code_coverage: true,
        result_bundle: true,
        destination: 'platform=macosx'
      )
    else
      scan(
        scheme: 'Birch-iOS-Unit-Tests',
        derived_data_path: 'DerivedData',
        code_coverage: true,
        result_bundle: true,
        device: opts[:device]
      )
    end
  end

  lane :release do
    version = read_podspec['version']

    pod_lib_lint(skip_tests: true)
    pod_push(allow_warnings: true, verbose: true)
  end
end
