default_platform :ios

platform :ios do
  lane :specs do
    scan(
      scheme: 'Birch-Unit-Tests',
      derived_data_path: 'DerivedData'
    )
  end

  lane :release do
    version = read_podspec['version']

    pod_lib_lint
    git_add
    git_commit message: "Version bump to #{version}"
    add_git_tag(tag: version)
    push_to_git_remote
    pod_push(allow_warnings: true, verbose: true)
  end
end