default_platform :ios

platform :ios do
  lane :specs do
    scan(
      scheme: 'Birch-Unit-Tests',
      derived_data_path: 'DerivedData',
      code_coverage: true,
      result_bundle: true
    )
  end

  lane :release do
    version = read_podspec['version']

    pod_lib_lint
    pod_push(allow_warnings: true, verbose: true)
  end
end