name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Cocoapods Lint
        run: bundle exec fastlane lint
      - name: Swift PM
        run: swift package describe
  specs:
    strategy:
      matrix:
        variant:
          - platform: ios
            xcode: /Applications/Xcode_15.1.app
            device: iPhone SE (3rd generation) (17.2)
          - platform: ios
            xcode: /Applications/Xcode_14.3.1.app
            device: iPhone 14 (16.4)
          - platform: tvos
            xcode: /Applications/Xcode_15.1.app
            device: Apple TV (17.2)
          - platform: tvos
            xcode: /Applications/Xcode_15.0.1.app
            device: Apple TV (16.4)
          - platform: macos
            xcode: /Applications/Xcode_15.1.app
    name: Specs
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Specs
        run: bundle exec fastlane specs platform:${{ matrix.variant.platform }} xcode:${{ matrix.variant.xcode }} device:"${{ matrix.variant.device }}"
      - uses: codecov/codecov-action@v3
        with:
          xcode: true
          xcode_archive_path: fastlane/test_output/Birch-${{ matrix.variant.platform }}-Unit-Tests.xcresult
